### ISSUE TITLE
Update to latest version of @jbrowse/react-linear-genome-view

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/JBrowseR#10]
get those latest "Bug fixes and improvements"

Anything special things we need to do to publish to CRAN ?

**Comment by nathanweeks** [comment]
There have been quite a few "bug fixes and improvements" between @jbrowse/react-linear-genome-view v2.0.1 and v2.4.2. Would it be straightforward to update JBrowseR to install the latest version, or does the R interface need to catch up to take advantage of any important added features?

**Comment by cmdcolin** [comment]
@nathanweeks thanks for reporting, @elliothershberg if you want to have a chat sometime maybe we can find a way to figure out a method for better continuous release...

**Comment by cmdcolin** [comment]
created https://github.com/GMOD/JBrowseR/issues/19 to track
