### ISSUE TITLE
Suggestions on JBrowseR

### ISSUE THREAD

**Issue by zhanxw** [GMOD/JBrowseR#13]
JBrowseR is very useful. However, I want to suggest two features:

1. tracks(...) needs to detect name collision. 
For example, when I add two VCF tracks, abc.prog1.vcf.gz and abc.prog2.vcf.gz, both will have the `name` values `abc`. Then the browser will not render either file correctly.
2. search by gene names.
currently, users can specify genomic location, but cannot search specific gene names. JBrowse CLI seems to support it (link: https://jbrowse.org/jb2/docs/combined/#indexing-feature-names-for-searching), but JBrowseR does not seem to support it now.

**Comment by elliothershberg** [comment]
Hey @zhanxw , thanks for both suggestions. We can work on incorporating these features.

**Comment by Spartanzhao** [comment]
Honestly, I think this tool is much worse that other tools that have been published, it's really hard to use, and I got lots of errors during installation. It's really useless to me.

**Comment by cmdcolin** [comment]
@Spartanzhao if you are interested in describing what errors you got, we can try to help. please avoid venting your frustrations like this though, it's not kind or helpful

**Comment by elliothershberg** [comment]
@cmdcolin this person just had a paper rejected in JOSS that I was a reviewer on. I think he's a bit upset about that.

It has reminded me, I need to find time this weekend to update JB2 in this package! 😄

**Comment by elliothershberg** [comment]
A new release is on its way to CRAN with a new function `text_index()` supporting gene name search.

Check out `example_apps/hg38_index_app.R` for example usage!

While it may be worth avoiding name collisions down the road, I haven't implemented this feature yet—it's probably best to avoid data files with duplicate names.
