### ISSUE TITLE
Add link to a live demo app with shinyapps.io

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/JBrowseR#16]
It could be fun/useful to give a live demo link with something like shinyapps.io. I have made at least one example of a shinyapps.io thing before and can try to help if interested!

**Comment by elliothershberg** [comment]
Nice, this is a good idea!

Do you have the link for the one you've already made?

**Comment by carolinebridge-oicr** [comment]
https://github.com/GMOD/jbrowse-components/pull/3732

**Comment by cmdcolin** [comment]
examples are in readme now
