### ISSUE TITLE
using UCSC plugin

### ISSUE THREAD

**Issue by bayolau** [GMOD/JBrowseR#17]
Thank you for your fantastic work!

I wonder if there's a way/example to use the UCSC plugin for jbrowse? https://github.com/cmdcolin/jbrowse-plugin-ucsc-api ? I've tried to modify the `js` code to pass in `plugins`, but it seems to have failed out because of a `new` operation on object.

```
plugins: [
  {
    "name": "UCSC",
    "url": "https://unpkg.com/jbrowse-plugin-ucsc/dist/jbrowse-plugin-ucsc.umd.production.min.js"
  }
]
```

**Comment by cmdcolin** [comment]
@bayolau hi there, I'm not aware of JBrowseR allowing you to add plugins yet

There is an example of using plugins with a plain instance of the jbrowse embedded linear genome view outside of JBrowseR  here https://jbrowse.org/storybook/lgv/main/?path=/story/using-plugins--page

might take a little work to add to JBrowseR, cc @elliothershberg

**Comment by bayolau** [comment]
@cmdcolin thanks! it works!

**Comment by cmdcolin** [comment]
excellent :) did it work inside of JBrowseR? or just stand alone?
