### ISSUE TITLE
Continuous or more frequent release process

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/JBrowseR#19]
Follow up to https://github.com/GMOD/JBrowseR/issues/10

**Comment by cmdcolin** [comment]
Just to open the discussion, we could make a formal process for producing JBrowseR releases by the core team if you wanted @elliothershberg

let me know if you'd like to meet to discuss :)

**Comment by elliothershberg** [comment]
Hey @cmdcolin ! Yeah, I think this would be worth setting up. I've got a crazy week, but let's find some time next week to plan this and get it working.

**Comment by cmdcolin** [comment]
sure thing. I am generally quite open. can also hop on our weekly wednesday call if you want (10am pst)

**Comment by elliothershberg** [comment]
Hey @carolinebridge-oicr definitely! Coordinating with Colin (we can also talk on Gitter or whatever is easiest).

**Comment by cmdcolin** [comment]
had a good chat with @elliothershberg 

main branch is now updated with latest build, and waiting for CRAN to transfer ownership now

**Comment by cmdcolin** [comment]
apparently CRAN is down right now (https://github.com/r-lib/devtools/issues/2527) but I documented the basic outline for publishing in PUBLISHING.md in both jbrowse-components and this repo
