### ISSUE TITLE
Add ability to use use a data.frame from R as a track in jbrowse 2?

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/JBrowseR#5]
I think there are lots of statistical analyses that are like "sliding window" are similarly computed quantitative tracks that are stored in data.frames and otherwise plotted with ggplot or similar

It would be nice to make these available for plotting as a track

Example Fst analysis
https://github.com/simonhmartin/genomics_general
https://speciationgenomics.github.io/per_site_Fst/

**Comment by elliothershberg** [comment]
Closed by #6 🎉
